"""initial_schema

Revision ID: 8f0e3b155a58
Revises: 
Create Date: 2026-05-06 23:11:46.039612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0e3b155a58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_signals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('signal', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_signals_id'), 'analysis_signals', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_signals_symbol'), 'analysis_signals', ['symbol'], unique=False)
    op.create_index(op.f('ix_analysis_signals_timeframe'), 'analysis_signals', ['timeframe'], unique=False)
    op.create_table('company_fundamentals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('roe', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('roa', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('operating_margin', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('net_profit_margin', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('gpa', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('per', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('pbr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('psr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('pcr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ev_ebitda', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('revenue_growth_yoy', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('operating_profit_growth_yoy', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('eps_growth_yoy', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('debt_ratio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('current_ratio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('interest_coverage', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('asset_turnover', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('dividend_payout_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('srim_intrinsic_value', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('srim_discount_rate', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('srim_equity_per_share', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('operating_profit', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('total_assets', sa.BigInteger(), nullable=True),
    sa.Column('total_equity', sa.BigInteger(), nullable=True),
    sa.Column('total_debt', sa.BigInteger(), nullable=True),
    sa.Column('eps', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_fundamentals_id'), 'company_fundamentals', ['id'], unique=False)
    op.create_index(op.f('ix_company_fundamentals_ticker_symbol'), 'company_fundamentals', ['ticker_symbol'], unique=True)
    op.create_table('ohlcv_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('high', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('low', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('close', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'candle_time', name='uq_ohlcv')
    )
    op.create_index(op.f('ix_ohlcv_data_candle_time'), 'ohlcv_data', ['candle_time'], unique=False)
    op.create_index(op.f('ix_ohlcv_data_id'), 'ohlcv_data', ['id'], unique=False)
    op.create_index(op.f('ix_ohlcv_data_symbol'), 'ohlcv_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_ohlcv_data_timeframe'), 'ohlcv_data', ['timeframe'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('kis_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('app_key_encrypted', sa.Text(), nullable=False),
    sa.Column('app_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kis_accounts_account_number'), 'kis_accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_kis_accounts_id'), 'kis_accounts', ['id'], unique=False)
    op.create_table('value_trend_scores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=False),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('profitability_score', sa.Float(), nullable=True),
    sa.Column('valuation_score', sa.Float(), nullable=True),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('safety_score', sa.Float(), nullable=True),
    sa.Column('dividend_score', sa.Float(), nullable=True),
    sa.Column('technical_signal', sa.String(length=20), nullable=True),
    sa.Column('is_above_kumo', sa.Boolean(), nullable=True),
    sa.Column('is_golden_cross', sa.Boolean(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticker_symbol'], ['company_fundamentals.ticker_symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_value_trend_scores_id'), 'value_trend_scores', ['id'], unique=False)
    op.create_index(op.f('ix_value_trend_scores_ticker_symbol'), 'value_trend_scores', ['ticker_symbol'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_user_symbol')
    )
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_purchase_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['kis_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', name='uq_account_symbol')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_table('trade_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('commission', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('tax', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('traded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['kis_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_history_id'), 'trade_history', ['id'], unique=False)
    op.create_index(op.f('ix_trade_history_symbol'), 'trade_history', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_history_symbol'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_id'), table_name='trade_history')
    op.drop_table('trade_history')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_value_trend_scores_ticker_symbol'), table_name='value_trend_scores')
    op.drop_index(op.f('ix_value_trend_scores_id'), table_name='value_trend_scores')
    op.drop_table('value_trend_scores')
    op.drop_index(op.f('ix_kis_accounts_id'), table_name='kis_accounts')
    op.drop_index(op.f('ix_kis_accounts_account_number'), table_name='kis_accounts')
    op.drop_table('kis_accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ohlcv_data_timeframe'), table_name='ohlcv_data')
    op.drop_index(op.f('ix_ohlcv_data_symbol'), table_name='ohlcv_data')
    op.drop_index(op.f('ix_ohlcv_data_id'), table_name='ohlcv_data')
    op.drop_index(op.f('ix_ohlcv_data_candle_time'), table_name='ohlcv_data')
    op.drop_table('ohlcv_data')
    op.drop_index(op.f('ix_company_fundamentals_ticker_symbol'), table_name='company_fundamentals')
    op.drop_index(op.f('ix_company_fundamentals_id'), table_name='company_fundamentals')
    op.drop_table('company_fundamentals')
    op.drop_index(op.f('ix_analysis_signals_timeframe'), table_name='analysis_signals')
    op.drop_index(op.f('ix_analysis_signals_symbol'), table_name='analysis_signals')
    op.drop_index(op.f('ix_analysis_signals_id'), table_name='analysis_signals')
    op.drop_table('analysis_signals')
    # ### end Alembic commands ###
