"""initial_schema

Revision ID: 5195ba45842f
Revises: 8f0e3b155a58
Create Date: 2026-05-17 17:13:22.520673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5195ba45842f'
down_revision: Union[str, None] = '8f0e3b155a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kis_accounts', sa.Column('balance', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('kis_accounts', sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kis_accounts', 'currency')
    op.drop_column('kis_accounts', 'balance')
    # ### end Alembic commands ###
